urls.py
from django.conf.urls import patterns, url
import apps.roll_call

urlpatterns = patterns('apps.roll_call.views',
  url(r'^$','entry' , name='entry'),
  url(r'^check/(?P<key>\d{1,5})/$','check',name='check'),
  url(r'^status/(?P<key>\d{1,5})/$','status',name='status'),
  url(r'^feedback/(?P<key>\d{1,5})/$', 'feedback', name="feedback"),
  url(r'^assignTeam/(?P<key>\d{1,5})/$', 'assignTeam', name="assignTeam"),
  url(r'^mylogout/', 'mylogout', name="mylogout"),
  url(r'^permission/', 'permission', name="permission"),
  url(r'^dorm/$', 'dorm', name="dorm"),
)

models.py
# -*- coding: utf-8 -*-
import django
from django.conf import settings
from django.db import models
from datetime import datetime
# 要取得會員的model要這樣寫
from oscar.core.compat import get_user_model
from apps.user.models import User
User = get_user_model()

# Create your models here.
class RCStu(models.Model):
  upperUser = models.OneToOneField(User)# 連結到系統的user帳號
  MALE = 'M'
  FEMALE = 'F'
  GENDER_CHOICES = (
    (MALE, 'Male'),
    (FEMALE, 'Female'),
  )
  # tuple的第一個元素是真正會被存入資料庫的資料，後面那個是顯示給人類看的
  gender = models.CharField(
      max_length=1,
      choices=GENDER_CHOICES,
      default=MALE,
  )
  studentID = models.CharField(max_length=20)
  name = models.CharField(max_length=10, default="Name")
  team = models.CharField(max_length=10)
  
  def __str__(self):
    return self.studentID+' 第'+self.team+'小隊'

  class Meta:
    permissions = (
      ("is_RC_staff", "是興鮮人的工作人員"),
    )

class RCRecord(models.Model):
  RCStu = models.ForeignKey(RCStu)
  RC_order = models.DecimalField(max_digits=2,decimal_places=0,default=1)
  create = models.DateTimeField()

  ROLLCALL_CHOICES = (
    (True,'出席', ),
    (False,'缺席', ),
  )
  present = models.BooleanField(choices=ROLLCALL_CHOICES,default=True)
  def __str__(self):
    return str(self.RCStu) + "在第" + str(self.RC_order) + "次點名" + "出席："+str(self.present)

class StudentST(models.Model):
  # 學員狀況
  RCStu = models.ForeignKey(RCStu)
  comment = models.CharField(max_length=100)
  create = models.DateTimeField()
  def __str__(self):
    return str(self.RCStu)

class StudentFD(models.Model):
  # RC回饋
  RCStu = models.ForeignKey(RCStu)
  feedback = models.CharField(max_length=100)
  create = models.DateTimeField()
  def __str__(self):
    return str(self.RCStu)

views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.shortcuts import render_to_response
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.utils import timezone # auto generate create time.
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import logout
from apps.roll_call.models import RCStu, RCRecord, StudentST, StudentFD
# 要取得會員的model要這樣寫
from oscar.core.compat import get_user_model
from apps.user.models import User
User = get_user_model()

def entry(request):
	return render_to_response('roll_call/entry/entry.html',locals())

@login_required
def check(request, key):
	teamRange = range(1,95)
	if request.POST:
		data = request.POST 
		data=data.dict()
		RCStuL = RCStu.objects.filter(team=key)
		# 篩選出該小隊的所有成員，然後沒有出現再request.post的資料裏面的就表示他是缺席，因為checkbox只會回傳有勾選的選項
		order = data['order'] # order是表示這是今天第幾次的點名（主辦單位再看一下時程表就可以知道這是幾點幾分的點名）
		d = {'RC_order' : order, 'create' : timezone.localtime(timezone.now())}
		for i in RCStuL:
			if i.studentID not in data:
				# 點名的時候因為學生都已經分配好小隊了，所以已經有屬於roll_call的table，以學號當作key，所以可以直接get
				d['present'] = True
				r = RCRecord.objects.update_or_create(RCStu=i, RC_order=order, defaults=d)
				# 因為可能會手誤點錯，所以是可以更新出席狀態的
			else:
				d['present'] = False
				r = RCRecord.objects.update_or_create(RCStu=i, RC_order=order, defaults=d)

	if key=='0':
		RCStuL = RCStu.objects.all()
		team = '所有'
		return render(request, 'roll_call/check/check.html', locals())

	else:
		RCStuL = RCStu.objects.filter(team=key).order_by('studentID')
		team = '第' + RCStuL[0].team
		userMajor = request.user.major
		return render(request, 'roll_call/check/checkTeam.html', locals())

@login_required
def assignTeam(request, key):
	teamRange = range(1,95)
	if request.POST:
		data = request.POST #all element of QuerySet is type of list, i dont know why but turn it into diction can disassembler its list into its origin type.
		data=data.dict()# turn Querydict into python's dict
		####Build default dict, if find data already exitst, than update the info. #####
		for i in data.items():
			#因為assignTeam顯示的會員資訊是帳號，也就是email，所以要先判斷是不是有包含@ (csrfToken沒有@)，若有則可以取出@前面的學號，再把學號存入roll_call當作key
			# _g代表是性別的資料
			if i[0].find('@') != -1 and i[1]!="":
				if '_team' in i[0]:
					foreignUser = User.objects.get(email=i[0].split('_team')[0])
					default = {'team' : i[1], 'upperUser':foreignUser}
					yourTeam = i[1]
					obj, created = RCStu.objects.update_or_create(studentID = i[0].split('@')[0], defaults=default)
					# update_or_create will update exist data or create a new one if doesn't exist.

				else:
					# 代表是性別的資料
					foreignUser = User.objects.get(email=i[0].split('_g')[0])
					default = {'gender' : i[1], 'upperUser':foreignUser}
					obj, created = RCStu.objects.update_or_create(studentID = i[0].split('@')[0], defaults=default)
		return redirect('roll_call:check', key=yourTeam)

	if request.GET!='' and 'major' in request.GET:
		m = request.GET.dict()['major']
		# print(User._meta.get_all_field_names())
		u = User.objects.filter(major=m, grade=1).order_by('email')
		me = request.user
		return render(request, 'roll_call/assignTeam/assignTeam.html', locals())

	if key=='0':
		return render(request, 'roll_call/assignTeam/assign.html', locals())

@login_required
def status(request, key):
	teamRange = range(1,95)
	if request.POST:
		data = request.POST 
		data=data.dict()
		rcs = RCStu.objects.get(studentID=data['stID']) 
		stustatus = StudentST.objects.create(RCStu=rcs, comment=data['cmt'], create=timezone.localtime(timezone.now()))

	if key=='0':
		RCStuL = RCStu.objects.all() 
		team = '所有'
		return render(request, 'roll_call/status/status.html', locals())

	else:
		RCStuL = RCStu.objects.filter(team=key) 
		team = '第' + RCStuL[0].team
		return render(request, 'roll_call/status/statusTeam.html', locals())

@login_required
def feedback(request, key):
	teamRange = range(1,95)
	if request.POST:
		data = request.POST 
		data=data.dict()
		rcs = RCStu.objects.get(studentID=(request.user.email).split('@')[0])
		# 想要知道request.user裏面有哪些值可以取用要看print(User._meta.get_all_field_names())  這些都是使用者帳號裏面有的資訊
		stufeedback = StudentFD.objects.create(RCStu=rcs, feedback=data['cmt'], create=timezone.localtime(timezone.now()))

	if key=='0':
		RCStuL = RCStu.objects.all() 
		team = '所有'
		return render(request, 'roll_call/feedback/feedback.html', locals())

	else:
		userMajor = request.user.major
		RCStuL = RCStu.objects.filter(team=key) 
		team = '第' + RCStuL[0].team
		return render(request, 'roll_call/feedback/feedbackTeam.html', locals())
def mylogout(request):
	logout(request)
	return redirect(reverse('roll_call:entry'))

@user_passes_test(lambda u: u.is_staff, login_url='/accounts/login/')
def permission(request):
	if request.POST:
		data = request.POST 
		data=data.dict()
		print(data)
		permitUser = User.objects.get(email=data['email'])
		permitUser.is_staff = True
		permitUser.save()
		permitUser = User.objects.get(email=data['email'])
		print(permitUser.is_staff)
		return render(request, 'roll_call/permission/permission.html', locals())		
	return render(request, 'roll_call/permission/permission.html', locals())

def dorm(request):
	return render(request, 'roll_call/dorm/dorm.html', locals())

templates/roll_call/assignTeam/assign.html
{% extends "roll_call/base/base.html"  %}
{% load staticfiles %}

{% block eachStyle %}
<link rel="stylesheet" type="text/css" href="{% static 'roll_call/toastr/toastr.css' %}">
{% endblock %}

{% block content %}
  {% block chooseDPT %}
    <form method="get" action="">
      <div class="form-group" id="degree_div">
          <label for="m_career" class="col-xs-2 control-label">學制</label>
          <div class="col-xs-10">
              <select class="form-control" name="m_career" id="m_career" form="register_form">
                  <option value="0">請選擇學制</option>
                  <option value="U">學士班</option>
                  <option value="G">碩士班</option>
                  <option value="D">博士班</option>
                  <option value="R">產專班</option>
                  <option value="W">碩專班</option>
                  <option value="N">進修學士班</option>
              </select>
          </div>
      </div>
      <div class="form-group" id="major_div">
          <label for="major" class="col-xs-2 control-label">系所</label>
          <div class="col-xs-10">
              <select class="form-control" name="major" id="major">
                  <option>請選擇系所</option>
              </select>
          </div>
      </div>
      <button class="ui button" type="submit">Submit</button>
    </form>
  {% endblock %}
  {% block assignTable %}
  {% endblock %}
{% endblock %}

{% block jsblock %}
<script src="{% static 'roll_call/js/assignTeam/dropdown.js' %}"></script>
<script src="{% static 'roll_call/toastr/toastr.js' %}"></script>
<script type="text/javascript">
  $(document).ready(function(){
    $('#submit').click(function(){
      toastr.info("提交中請稍候", {timeOut: 2500});
    })
  })
</script>
{% include 'course/js_script_tag.html' %}
{% endblock %}

templates/roll_call/assignTeam/assignTeam.html
{% extends "roll_call/assignTeam/assign.html"  %}
{% load staticfiles %}

{% block eachStyle %}
<link rel="stylesheet" type="text/css" href="{% static 'roll_call/toastr/toastr.css' %}">
{% endblock %}

{% block assignTable %}
<h1>分配小隊~</h1>

<form class="ui form" action="" method="post">
  {% csrf_token %}
  <table class="ui inverted unstackable green table">
    <thead>
      <tr>
      <th>學號</th>
      <th>性別</th>
      <th>小隊</th>
  	  </tr>
    </thead>
    <tbody>

    <tr style="color:red">
      <td style="color:red">{{me.email}}</td>
      <td>
        <div class="ui fluid search selection dropdown">
          <input type="hidden" name="{{me.email}}_g">
          <!--{s}_g指的是該小隊員的性別-->
          <i class="dropdown icon"></i>
          <div class="default text" style="display: flex;">選擇性別</div>
          <div class="menu">
            <div class="item" data-value="M" style="display: flex;">
              <img src="{% static 'roll_call/img/worker.svg' %}">
              <span>男</span>
            </div>
            <div class="item" data-value="F" style="display: flex;">
              <img src="{% static 'roll_call/img/woman.svg' %}">
              <span>女</span>
            </div>
          </div>
        </div> 
      </td>

      <td>
        <div class="ui fluid search selection dropdown">
          <input type="hidden" name="{{me.email}}_team">
          <i class="dropdown icon"></i>
          <div class="default text">選擇小隊</div>
          <div class="menu">
            {% for i in teamRange %}
              <div class="item" data-value={{i}}><i class="tw flag"></i>{{i}}</div>
            {% endfor %}
          </div>
        </div> 
      </td>
    </tr>

    {% for s in u %}
      <tr>
        <td>{{s.email}}</td>
        <td>
          <div class="ui fluid search selection dropdown">
            <input type="hidden" name="{{s.email}}_g">
            <!--{s}_g指的是該小隊員的性別-->
            <i class="dropdown icon"></i>
            <div class="default text" style="display: flex;">選擇性別</div>
            <div class="menu">
              <div class="item" data-value="M" style="display: flex;">
                <img src="{% static 'roll_call/img/worker.svg' %}">
                <span>男</span>
              </div>
              <div class="item" data-value="F" style="display: flex;">
                <img src="{% static 'roll_call/img/woman.svg' %}">
                <span>女</span>
              </div>
            </div>
          </div> 
        </td>

        <td>
      	  <div class="ui fluid search selection dropdown">
      	    <input type="hidden" name="{{s.email}}_team">
      	    <i class="dropdown icon"></i>
      	    <div class="default text">選擇小隊</div>
      	    <div class="menu">
              {% for i in teamRange %}
        	      <div class="item" data-value={{i}}><i class="tw flag"></i>{{i}}</div>
              {% endfor %}
      	    </div>
      	  </div> 
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  <button class="ui button" type="submit" id="submit">Submit</button>
</form>
	
{% endblock %}

{% block jsblock %}
<script src="{% static 'roll_call/js/assignTeam/dropdown.js' %}"></script>
<script src="{% static 'roll_call/toastr/toastr.js' %}"></script>
<script type="text/javascript">
  $(document).ready(function(){
    $('#submit').click(function(){
      toastr.info("提交中請稍候", {timeOut: 2500});
    })
  })
</script>
{% include 'course/js_script_tag.html' %}
{% endblock %}

templates/roll_call/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>{% block title %}興鮮人{% endblock %}</title>    
	<link rel="icon" href="{% static 'roll_call/nchu_sg.jpg' %}" type="image/ico" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- 引入CSS -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.6/semantic.min.css">
	<!-- navbar的特效以及css-->
	<link rel="stylesheet" type="text/css" href="{% static 'roll_call/css/sidebar.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'roll_call/css/entry.css' %}">
	{% block eachStyle %}{% endblock %}
</head>
<body>
<!-- Following Menu -->
{% include "roll_call/base/leftBar.html" %}

{% block body %}
<div class="pusher">
	<div class="ui inverted  aligned segment">
		{% include "roll_call/base/topBar.html" %}
	</div>

	{% block content %}
	{% endblock %}

</div>
{% endblock %}

{% include "roll_call/base/footer.html" %}
</body>

<!-- 引入Ｊs TAG -->
<!-- 引入Ｊquery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<!-- 引入Ｊs -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.6/semantic.min.js"></script>
<script src="{% static 'roll_call/js/pusher.js' %}"></script>
<script src="{% static 'roll_call/js/visibility.js' %}"></script>
<script src="{% static 'roll_call/js/sidebar.js' %}"></script>
<script src="{% static 'roll_call/js/transition.js' %}"></script>
<!-- 引入Ｊs TAG -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-78099072-4', 'auto');
  ga('send', 'pageview');

</script>
{% block jsblock %}{% endblock %}
</html>

templates/roll_call/base/footer.html
<!--  footer -->
<div class="ui  inverted vertical footer segment">
	<div class="ui center aligned container">
		<div class="ui horizontal inverted large divided  list">
			<span>Copyright © 2016 All rights reserved.</span>
			<a href="https://www.facebook.com/CoursePickingHelper/"><i class="facebook square icon large link" ></i></a>
		</div>
	</div>
</div>

templates/roll_call/base/leftBar.html
<!-- Sidebar Menu -->
<div class="ui vertical inverted sidebar menu">
  {% block leftBar %}
    <a class="active item" href="{% url 'entry:entry' %}">Home</a>
    {% if request.user.is_staff %}
      <a class="item" href="{% url 'roll_call:check' key=0 %}">出席狀況</a>
      <a class="item" href="{% url 'roll_call:status' key=0 %}">學員狀況</a>
      <a class="item" href="{% url 'roll_call:assignTeam' key=0 %}">分配小隊</a>
    {% endif %}
    <a class="item" href="{% url 'roll_call:feedback' key=0 %}">意見回應</a>
    {% if request.user.is_authenticated %}
      <a class="ui inverted button">HI {{request.user}}</h4>
      <a class="ui inverted button" href="{% url 'roll_call:mylogout' %}">Log out</a>
    {% else %}
      <a class="ui inverted button" href="/zh-tw/accounts/login/?next=/roll_call/">Log in/Sign Up</a>
    {% endif %}
  {% endblock %}
</div>

templates/roll_call/base/topBar.html
<div class="ui container">
  <div class="ui large secondary inverted pointing menu">
    <a class="toc item">
      <i class="sidebar icon"></i>
    </a>
    {% block topBar %}
      <a class="active item" href="{% url 'entry:entry' %}">Home</a>
      {% if request.user.is_staff %}
        <a class="item" href="{% url 'roll_call:check' key=0 %}">出席狀況</a>
        <a class="item" href="{% url 'roll_call:status' key=0 %}">學員狀況</a>
        <a class="item" href="{% url 'roll_call:assignTeam' key=0 %}">分配小隊</a>
      {% endif %}
      <a class="item" href="{% url 'roll_call:feedback' key=0 %}">意見回應</a>
      <div class="right item">
        {% if request.user.is_authenticated %}
          <a class="ui inverted button">HI {{request.user}}</h4>
          <a class="ui inverted button" href="{% url 'roll_call:mylogout' %}">Log out</a>
        {% else %}
          <a class="ui inverted button" href="/zh-tw/accounts/login/?next=/roll_call/">Log in/Sign Up</a>
        {% endif %}
      </div>
    {% endblock %}
  </div>
</div>

templates/roll_call/check/check.html
{% extends "roll_call/base/base.html"  %}
{% load staticfiles %}

{% block eachStyle %}
	<link rel="stylesheet" type="text/css" href="{% static 'roll_call/toastr/toastr.css' %}">
{% endblock %}

{% block content %}
	<div class="ui floating dropdown labeled search icon button">
	  <i class="world icon"></i>
	  <span class="text">{{team}}小隊的點名頁面</span>
	  <div class="menu">
		{% for t in teamRange %}
		<a class="item" href="/roll_call/check/{{t}}">
		  <img class="ui avatar image" src="{% static 'roll_call/nchu_sg.jpg'%}">
		  {{ t }}
		</a>
		{% endfor %}
	  </div>
	</div>

	{% block form %}
		
	{% endblock %}

	<table class="ui very basic collapsing celled table stackable">
	  <thead>
		<tr><th>小隊員出席</th>
		<th>出席狀況</th>
	  </tr></thead>
	  <tbody>
		{% for i in RCStuL %}
			<tr>
			  {% for j in i.rcrecord_set.all|dictsort:"RC_order"  %}
			  	  <!--要用foreignKey取到連結的model，|dictsort:"RC_order"是排序的filter，會用dict裏面的key來排序，key名稱放後面的字串-->
				  {% if forloop.first %}
					  <td>
						<h4 class="ui image header">
						  {% if i.gender == "M" %}
						  	<img src="{% static 'roll_call/img/worker.svg' %}" class="ui mini rounded image">
						  {% else %}
						  	<img src="{% static 'roll_call/img/woman.svg' %}" class="ui mini rounded image">
						  {% endif %}	
						  <div class="content">
							{{i.upperUser.name}}
							<div class="sub header">{{i.studentID}}</div>
						  </div>
						</h4>
					  </td>
					  <td>
					  	{% if j.present %}
							{{j.RC_order}}<img src="{% static 'roll_call/img/checked.svg' %}" class="ui mini rounded image">
						{% else %}
							{{j.RC_order}}<img src="{% static 'roll_call/img/unchecked.svg' %}" class="ui mini rounded image">
						{% endif %}
					  </td>
				  {% else %}
					  <td>
					  	{% if j.present %}
							{{j.RC_order}}<img src="{% static 'roll_call/img/checked.svg' %}" class="ui mini rounded image">
						{% else %}
							{{j.RC_order}}<img src="{% static 'roll_call/img/unchecked.svg' %}" class="ui mini rounded image">
						{% endif %}
					  </td>
				  {% endif %}
			  {% endfor %}
			</tr>
		{% endfor %}
	  </tbody>
	</table>

{% endblock %}

{% block jsblock %}
	<script src="{% static 'roll_call/js/assignTeam/dropdown.js' %}"></script>
	<script src="{% static 'roll_call/toastr/toastr.js' %}"></script>
	<script type="text/javascript">
	  $(document).ready(function(){
		$('#submit').click(function(){
		  toastr.info("提交中請稍候", {timeOut: 2500});
		})
	  })
	</script>
{% endblock %}

templates/roll_call/feedback/feedback.html
{% extends "roll_call/base/base.html"  %}
{% load staticfiles %}

{% block eachStyle %}
	<link rel="stylesheet" type="text/css" href="{% static 'roll_call/toastr/toastr.css' %}">
{% endblock %}

{% block content %}
	{% block dropdown %}
	<div class="ui floating dropdown labeled search icon button">
	  <i class="world icon"></i>
	  <span class="text">{{team}}小隊的意見回應</span>
	  <div class="menu">
		{% for t in teamRange %}
		<a class="item" href="/roll_call/feedback/{{t}}">
		  <img class="ui avatar image" src="{% static 'roll_call/nchu_sg.jpg'%}">
		  {{ t }}
		</a>
		{% endfor %}
	  </div>
	</div>
	{% endblock %}

	{% block form %}
		
	{% endblock %}

	<div class="ui comments">
	  <h3 class="ui dividing header">意見回應</h3>
	  {% for i in RCStuL %}
		    {% for j in i.studentfd_set.all|dictsort:"create"  %}
		      <div class="comment">
		          <a class="avatar">
		            {% if i.gender == "M" %}
		            	<img src="{% static 'roll_call/img/worker.svg' %}" class="ui mini rounded image">
		            {% else %}
		            	<img src="{% static 'roll_call/img/woman.svg' %}" class="ui mini rounded image">
		            {% endif %}	
		          </a>
		          <div class="content">
		            <a class="author">{{i.upperUser.name}}</a>
		            <div class="metadata">
		              <div class="date">{{j.create}}</div>
		            </div>
		            <div class="text">
		              <p>{{j.feedback}}</p>
		            </div>
		            <div class="actions">
		              <a class="reply">Reply</a>
		            </div>
		          </div>
		        </div>
		  {% endfor %}
	  {% endfor %}
	</div>

{% endblock %}

{% block jsblock %}
	<script src="{% static 'roll_call/js/assignTeam/dropdown.js' %}"></script>
	<script src="{% static 'roll_call/toastr/toastr.js' %}"></script>
	<script type="text/javascript">
	  $(document).ready(function(){
		$('#submit').click(function(){
		  toastr.info("提交中請稍候", {timeOut: 2500});
		})
	  })
	</script>
{% endblock %}

templates/roll_call/permission/permission.html
{% extends "roll_call/base/base.html"  %}

{% block content %}
<form class="ui reply form" action="" method="post">
{% csrf_token %}
<div class="ui inverted green segment">
  <div class="ui inverted form">
    <div class="inline field">
      <div class="field">
        <input name="email" placeholder="請填入要給予權限的使用者email"></input>
      </div>
    </div>
    <button class="ui button" type="submit" id="submit">Submit</button>
  </div>
</div>
</form>
{% endblock %}

templates/roll_call/status/status.html
{% extends "roll_call/base/base.html"  %}
{% load staticfiles %}

{% block eachStyle %}
	<link rel="stylesheet" type="text/css" href="{% static 'roll_call/toastr/toastr.css' %}">
{% endblock %}

{% block content %}
	{% block dropdown %}
	<div class="ui floating dropdown labeled search icon button">
	  <i class="world icon"></i>
	  <span class="text">{{team}}小隊的學員狀況</span>
	  <div class="menu">
		{% for t in teamRange %}
		<a class="item" href="/roll_call/status/{{t}}">
		  <img class="ui avatar image" src="{% static 'roll_call/nchu_sg.jpg'%}">
		  {{ t }}
		</a>
		{% endfor %}
	  </div>
	</div>
	{% endblock %}

	{% block form %}
		
	{% endblock %}

	<div class="ui comments">
	  <h3 class="ui dividing header">學員狀況</h3>
	  {% for i in RCStuL %}
		    {% for j in i.studentst_set.all|dictsort:"create"  %}
		      <div class="comment">
		          <a class="avatar">
		            {% if i.gender == "M" %}
		            	<img src="{% static 'roll_call/img/worker.svg' %}" class="ui mini rounded image">
		            {% else %}
		            	<img src="{% static 'roll_call/img/woman.svg' %}" class="ui mini rounded image">
		            {% endif %}	
		          </a>
		          <div class="content">
		            <a class="author">{{i.upperUser.name}}</a>
		            <div class="metadata">
		              <div class="date">{{j.create}}</div>
		            </div>
		            <div class="text">
		              <p>{{j.comment}}</p>
		            </div>
		            <div class="actions">
		              <a class="reply">Reply</a>
		            </div>
		          </div>
		        </div>
		  {% endfor %}
	  {% endfor %}
	</div>

{% endblock %}

{% block jsblock %}
	<script src="{% static 'roll_call/js/assignTeam/dropdown.js' %}"></script>
	<script src="{% static 'roll_call/toastr/toastr.js' %}"></script>
	<script type="text/javascript">
	  $(document).ready(function(){
		$('#submit').click(function(){
		  toastr.info("提交中請稍候", {timeOut: 2500});
		})
	  })
	</script>
{% endblock %}

templates/roll_call/status/statusTeam.html
{% extends "roll_call/status/status.html"  %}
{% load staticfiles %}
{% block dropdown %}{% endblock %}
{% block form %}
<form class="ui reply form" action="" method="post">
{% csrf_token %}
<div class="ui inverted segment">
  <div class="ui inverted form">
    <div class="two fields">
      <div class="field">
        <label>學號</label>
        <input placeholder="學號" type="text" name="stID">
      </div>
    </div>
    <div class="inline field">
      <div class="field">
        <textarea name="cmt"></textarea>
      </div>
    </div>
    <button class="ui button" type="submit" id="submit">Submit</button>
  </div>
</div>
</form>
{% endblock %}